Publish Microsoft Authored templates to azure samples browser
Azure-Samples/svc-invoke-dapr-csharp pull request #5
Opened 2024-01-15 07:32 UTC by v-xuto

Publish `svc-invoke-dapr-csharp` template to azure samples browser.

@rajeshkamal5050 and @hemarina for notification.

2024-01-16 23:56 UTC, hemarina approved these changes
LGTM. @greenie-msft for notification. Could you review this PR?

2024-01-22 06:27 UTC, v-xuto commented
@greenie-msft Could you help review this PR and merge it if it looks good?

2024-02-04 07:36 UTC, v-xuto commented
@greenie-msft Could you help review this PR and merge it if it looks good? Thanks in advance.

2024-04-25 21:17 UTC, hemarina commented
@tonybaloney Would you mind review this PR?

2024-04-29 21:46 UTC, tonybaloney requested changes

2024-04-29 21:46 UTC, tonybaloney commented on README.md
> +name: Microservice communication using service invoke (C#)
```suggestion
name: Microservice communication using Dapr's Service Invocation API (C#)
```

2024-05-10 06:36 UTC, v-xuto commented
@tonybaloney I have updated by your comments, please re-review.

2024-06-06 03:46 UTC, tonybaloney approved these changes

2024-06-06 03:46 UTC, merged